#!/bin/bash

[[ -f ~/.theme ]] && . ~/.theme

# General config
bspc config focused_border_color "$background"
bspc config normal_border_color "$color8"
bspc config presel_feedback_color "$accent"
bspc config border_width "$border_width"
bspc config window_gap "$window_gap"
bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config initial_polarity second_child
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner

# Desktops
bspc monitor -d 1 2 3 4 5 6 web chat files
bspc desktop web -l monocle
for side in left right; do bspc config -d chat "$side"_padding 150; done

# Rules
bspc rule -r '*:*'
for class in feh mpv File-roller Deluge Fcitx-config-gtk3 Lxappearance Pavucontrol \
             URxvt:{info,wifi,calendar} Rofi Qemu-system-x86_64; do
    bspc rule -a "$class" state=floating
done
bspc rule -a Firefox desktop=web follow=on
bspc rule -a URxvt:chat desktop=chat follow=on
bspc rule -a URxvt:files desktop=files follow=on
bspc rule -a Pcmanfm desktop=files follow=on
bspc rule -a URxvt:editor follow=on
bspc rule -a teeworlds state=fullscreen
[[ -x ~/.config/bspwm/rules ]] && bspc config external_rules_command ~/.config/bspwm/rules

# Bar
killall -q bar
bar &

# Notification manager
killall -q dunst
dunst &
