# X settings
setxkbmap -option grp:shifts_toggle,compose:menu fr,us,ru,gr oss,,,
[[ -f ~/.Xmodmap ]] && xmodmap ~/.Xmodmap
numlockx
xset -b
xset r rate 250
xsetroot -cursor_name left_ptr
refresh xresources

# Key bindings
sxhkd &

# Wallpaper
refresh wallpaper

# Compositing manager
picom -b &

# Blue light filter
redshift &

# rofi fav list
rofl &

# xkcd watcher
xkcd &

# Polkit agent
/usr/lib/mate-polkit/polkit-mate-authentication-agent-1 &

# Window manager
bspwm

# Cleanup
killall -q bar
