#!/bin/bash
#
# brightness - get/set the screen's brightness

shopt -s nullglob

if [[ ! -e $backlight ]]; then
    backlights=(/sys/class/backlight/acpi_video0*)
    (( ${#backlights[@]} )) || exit 1
    backlight=${backlights[0]}
fi

max_brightness=$(< "$backlight"/max_brightness)
brightness=$(< "$backlight"/brightness)
percentage=$(( brightness * 100 / max_brightness ))

(( step = max_brightness / 50 ))
(( step >= 1 )) || (( step = 1 ))

if (( ! $# )); then
    printf '%s\n' "$percentage"
else
    case $1 in
        -) (( brightness -= step ));;
        +) (( brightness += step ));;
        *) (( brightness = $1 * max_brightness / 100 ));;
    esac
    if (( brightness < 0 )); then
        (( brightness = 0 ))
    elif (( brightness > max_brightness )); then
        (( brightness = max_brightness ))
    fi
    printf '%s' "$brightness" > "$backlight"/brightness 2> /dev/null
fi
