#!/bin/bash
#
# details - display system info

[[ $1 == -v ]] || exec 2> /dev/null

[[ -f ~/.theme ]] && . ~/.theme

# Variables

kernel=$(uname -r)
kernel=${kernel%%-*}

os=$(. /etc/os-release && echo "$ID")

packages=$(pacman -Qq | wc -l)

shell=${SHELL##*/}

id=$(xprop -root _NET_SUPPORTING_WM_CHECK | grep -o '0x\w*')
wm=$(xprop -id "$id" _NET_WM_NAME | cut -d \" -f 2)
wm=${wm,,}

term=$(xprop -id "$WINDOWID" WM_CLASS | cut -d \" -f 4)
term=${term,,}

IFS=':' read -rd ',' prefix font _ <<< "$font"
[[ $prefix == xft ]] || font=$prefix
font=${font##* }

# Display

space=10
#sep=' ┃ '
sep=' = '
bold=$(tput bold)
reset=$(tput sgr0)

info() {
    [[ $2 ]] && printf '%s%*s%s%s%s\n' "$bold" "$space" "$1" "$reset" "$sep" "$2"
}

echo
ascii camera | lolcat -o 600
echo
info kernel "$kernel"
info os "$os"
info pkg "$packages"
info shell "$shell"
info wm "$wm"
info term "$term"
info font "$font"
echo
