#!/bin/bash
#
# details - display system info

[[ $1 == -v ]] || exec 2> /dev/null

[[ -f ~/.theme ]] && . ~/.theme

# Variables

os=$(. /etc/os-release && printf '%s' "$ID")

kernel=$(uname -r)
kernel=${kernel%%-*}

packages=$(pacman -Qq | wc -l)

shell=${SHELL##*/}

id=$(xprop -root _NET_SUPPORTING_WM_CHECK | grep -o '0x\w*')
wm=$(xprop -id "$id" _NET_WM_NAME | cut -d \" -f 2)
wm=${wm,,}

term=$(xprop -id "$WINDOWID" WM_CLASS | cut -d \" -f 4)
term=${term,,}

font=${font##* }
font=${font,,}

# Display

space=10
sep=' '
bold=$(tput bold)
reset=$(tput sgr0)

info() {
    [[ $2 ]] && printf '%s%*s%s%s%s\n' "$bold" "$space" "$1" "$reset" "$sep" "$2"
}

ascii triangle | lolcat -o 600
info os "$os"
info kernel "$kernel"
info pkg "$packages"
info shell "$shell"
info wm "$wm"
info term "$term"
info font "$font"
echo
