#!/bin/bash
#
# details - display system info

shopt -s lastpipe

[[ $1 == -v ]] || exec 2> /dev/null

[[ -f ~/.theme ]] && . ~/.theme

space=10
sep=' '
bold=$(tput bold) reset=$(tput sgr0)

print() {
    [[ $2 ]] && printf '%s%*s%s%s%s\n' "$bold" "$space" "$1" "$reset" "${3:-$sep}" "$2"
}

echo
print "$USER" "$HOSTNAME" @
echo

(. /etc/os-release && print os "$ID")

kernel=$(uname -r)
print kernel "${kernel%%-*}"

print packages "$(pacman -Qq | wc -l)"

print shell "${SHELL##*/}"

xprop -root -notype ' $0\n' _NET_SUPPORTING_WM_CHECK | read -r _ id
xprop -id "$id" ' $0\n' _NET_WM_NAME | IFS+='"' read -r _ wm
print wm "${wm,,}"

xprop -id "$WINDOWID" ' $1\n' WM_CLASS | IFS+='"' read -r _ term
print term "${term,,}"

font=${font##* }
print font "${font,,}"

echo
