#!/usr/bin/env bash

shopt -s lastpipe

wm_data=$(bspc wm -d)
nodes=()
jq <<< "$wm_data" -r --arg class "$class" --arg instance "$instance" '
    .monitors[].desktops[].root//empty |
    recurse(.firstChild//empty, .secondChild//empty) |
    select(.client != null) |
    select($class == "" or (.client.className | test($class; "i"))) |
    select($instance == "" or (.client.instanceName | test($instance; "i"))) |
    .id
' |
while read -r node; do
    [[ ! $title || $(xtitle "$node") =~ $title ]] && nodes+=("$node")
done

(( ${#nodes[@]} )) || exit

jq <<< "$wm_data" -r '
    .focusHistory |
    reduce to_entries[] as {$key, value: {$nodeId}} (
        $ARGS.positional | map({key: ., value: -1}) | from_entries;
        (.[$nodeId | tostring]//empty) = $key
    ) | to_entries | min_by(.value).key
' --args "${nodes[@]}" |
read -r node

bspc node "$node" -f
