#!/bin/bash
#
# game - launch a game via Steam

game=$1

declare -A ids=(
    [ftl]=212680
    [hld]=257850
    [isaac]=113200
    [portal2]=620
    [portal]=400
    [teeworlds]=380840
    [tmnf]=11020
)

if ! pgrep -f /usr/lib/steam/steam > /dev/null; then
    steam -silent &> /dev/null &
    sleep 20
fi

case $game in
    terraria)
        layout_saved=$(xkblayout-state print %c)
        xkblayout-state set 1
        { sleep 5; exec xkblayout-state set "$layout_saved"; } &
        exec ~/.local/share/Steam/steamapps/common/Terraria/Terraria -autoarch
        ;;
    *)
        exec steam -applaunch "${ids[$game]}"
        ;;
esac

echo "Couldn't launch $game." >&2
exit 1
