#!/bin/bash
#
# git-sync - sync local repositories with a set of remotes
# TODO: move remotes definitions to a config file

declare -A should_sync
for repo do should_sync[$repo]=1; done

declare -A remotes=(
    [~/git/aur/efont-unicode-bdf]='ssh://aur@aur.archlinux.org/efont-unicode-bdf.git'
    [~/.local/share/emojilib]='https://github.com/muan/emojilib'
)

while read -r repo; do
    if [[ $repo == dotfiles ]]; then
        dir=~/.dots
    else
        dir=~/git/$repo
    fi
    remotes[$dir]="gitea@git.monade.li:n/$repo.git"
done < <(curl -fsSL https://git.monade.li/api/v1/users/n/repos | jq -r '.[].name')

for dir in "${!remotes[@]}"; do
    (( $# && ! should_sync[${dir##*/}] )) && continue
    printf '%s %s\n' "$(tput bold; tput setaf 2)==>$(tput sgr0)" "$dir"
    if [[ -d $dir/.git ]]; then
        git -C "$dir" pull --rebase
    else
        git clone "${remotes[$dir]}" "$dir"
    fi
done
