#!/usr/bin/env bash

terminal() {
    local instance title focus_title columns lines hold
    [[ $instance ]] && class=alacritty instance="$instance" focus && return
    [[ $focus_title ]] && class=alacritty title="$focus_title" focus && return
    alacritty \
        ${instance:+--class "$instance"} \
        ${title:+--title "$title"} \
        ${columns:+-o window.dimensions.columns="$columns"} \
        ${lines:+-o window.dimensions.lines="$lines"} \
        ${hold:+--hold} \
        ${*:+-e "$@"}
}

# If -n is given, always create a new instance
if [[ $1 == -n ]]; then
    focus() { return 1; }
    shift
fi

case $1 in
    term|terminal)
        terminal &;;
    irc)
        instance=irc terminal autossh -M 0 -- -qt monade.li tmux -L weechat attach &;;
    text|editor)
        focus_title='- VIM$' terminal vim &;;
    wifi)
        instance=wifi title=wifi columns=50 lines=25 terminal sudo wifi-menu &;;
    info|details)
        instance=info columns=23 lines=12 BASH_STARTUP=details terminal &;;
    web|browser)
        class=firefox focus || { firefox & };;
    mail)
        class=thunderbird focus || { thunderbird & };;
    files)
        class=thunar focus || { thunar & };;
    video)
        class=mpv focus;;
    volume)
        class=pavucontrol focus || { pavucontrol & };;
    jap|japanese)
        pkill -x fcitx || { fcitx & };;
    cal|calendar)
        instance=calendar title=calendar columns=64 lines=9 hold=1 terminal cal -3 &;;
esac
