#!/bin/bash
#
# le - focus/launch stuff

# If -n is given, always create a new instance
if [[ $1 == -n ]]; then
    focus() {
        return 1
    }
    shift
fi

case $1 in
    '')
        printf '%s\n' term irc text wifi info web mail files music video volume jap
        ;;
    term|terminal)
        urxvt &
        ;;
    irc)
        focus urxvt -i irc || { urxvt -name irc -title irc -e ssh -qt monade.li tmux -L weechat attach & }
        ;;
    text|editor)
        focus urxvt -n '* - vim' || { urxvt -name editor -e vim & }
        ;;
    wifi)
        focus urxvt -i wifi || { urxvt -name wifi -title wifi -geometry 50x25 -e sudo wifi-menu & }
        ;;
    info|details)
        BASH_STARTUP='details' urxvt -name info -geometry 23x12 &
        ;;
    web|browser)
        focus firefox || { firefox & }
        ;;
    mail)
        #xdg-open 'https://mail.google.com/' &
        focus thunderbird || { thunderbird & }
        ;;
    files)
        focus thunar || { thunar & }
        ;;
    video)
        focus mpv
        ;;
    volume)
        focus pavucontrol || { pavucontrol & }
        ;;
    jap|japanese)
        pkill -x fcitx || { fcitx & }
        ;;
esac
