#!/usr/bin/env bash
#
# le - focus/launch stuff

# If -n is given, always create a new instance
if [[ $1 == -n ]]; then
    focus() {
        return 1
    }
    shift
fi

case $1 in
    '')
        printf '%s\n' term irc text wifi info web mail files music video volume jap cal
        ;;
    term|terminal)
        alacritty &
        ;;
    irc)
        focus alacritty -i irc || { MOSH_TITLE_NOPREFIX=1 alacritty --class irc -e mosh monade.li -- tmux -L weechat attach & }
        ;;
    text|editor)
        focus alacritty -n '* - vim' || { alacritty --class editor -e vim & }
        ;;
    wifi)
        focus alacritty -i wifi || { alacritty --class wifi --title wifi -o window.dimensions.columns=50 window.dimensions.lines=25 -e sudo wifi-menu & }
        ;;
    info|details)
        BASH_STARTUP='details' alacritty --class info -o window.dimensions.columns=23 window.dimensions.lines=12 &
        ;;
    web|browser)
        focus firefox || { firefox & }
        ;;
    mail)
        #xdg-open 'https://mail.google.com/' &
        focus thunderbird || { thunderbird & }
        ;;
    files)
        focus thunar || { thunar & }
        ;;
    video)
        focus mpv
        ;;
    volume)
        focus pavucontrol || { pavucontrol & }
        ;;
    jap|japanese)
        pkill -x fcitx || { fcitx & }
        ;;
    cal|calendar)
        alacritty --class calendar -o window.dimensions.columns=64 window.dimensions.lines=9 cursor.style=underline --hold -e cal -3
        ;;
esac
