#!/bin/bash
#
# music - a music player interface

shopt -s lastpipe nocasematch

dmenu() {
    rofi -dmenu -i -matching fuzzy "$@"
}

mpc() {
    command mpc -q "$@"
}

if (( $# )); then
    mpc clear
    for f do
        if ! mpc add "${f##*/}" 2> /dev/null; then
            mpc clear
            exec mpv --player-operation-mode=pseudo-gui -- "$@"
        fi
    done
    mpc play
else
    filter=()
    declare -A filter_has=()

    { echo all; mpc list artist; } |
    dmenu -p artist -format i/s |
    IFS=/ read -r index artist || exit 1

    if (( index > 0 )); then
        filter+=(artist "$artist")
        filter_has[artist]=1
    fi

    { echo all; mpc list album "${filter[@]}"; } |
    dmenu -p album -format i/s |
    IFS=/ read -r index album || exit 1

    if (( index > 0 )); then
        filter+=(album "$album")
        filter_has[album]=1
    fi

    mpc clear

    if (( ${#filter[@]} )); then
        mpc random off
        mpc findadd "${filter[@]}"
    else
        mpc random on
        mpc add /
    fi

    lines=$(mpc playlist | wc -l)
    (( lines > 15 )) && lines=15

    format='%title%|%file%'
    if [[ -v 'filter_has[album]' ]]; then
        format='[%track% - ]'$format
    elif [[ -v 'filter_has[artist]' ]]; then
        format='[%album% - ]'$format
    else
        format='[%artist% - ]'$format
    fi

    mpc playlist -f "$format" |
    dmenu -p song -format d -lines "$lines" |
    read -r index || exit 1

    mpc play "$index"
fi
