#!/usr/bin/env bash
#
# musicart - display album art for the currently playing song

current=$(mpc current -f %file%)

[[ $current ]] || exit

cover=$(mktemp --suffix .png) || exit 1
trap 'rm -f -- "$cover"' exit

ffmpeg -loglevel error -nostdin -y -i "$(xdg-user-dir MUSIC)/$current" -map 0:v:0 "$cover" || exit

feh -. -g 500x500 -- "$cover"
