#!/bin/bash
#
# power - rofi power menu

case $(printf '%s\n' shutdown reboot suspend logout | rofi -dmenu -p action -lines 4 -width 200) in
    shutdown) systemctl poweroff;;
    reboot) systemctl reboot;;
    suspend) systemctl suspend;;
    logout) bspc quit;;
esac
