#!/usr/bin/env bash

wallpaper=$(shuf -n 1 -e ~/pictures/horizontal/* ~/pictures/tileable/*)

case $wallpaper in
    ~/pictures/horizontal/*)
        feh --bg-fill "$wallpaper";;
    ~/pictures/tileable/*)
        feh --bg-tile "$wallpaper";;
esac
