#!/usr/bin/env bash

pictures=$(xdg-user-dir PICTURES)
wallpaper=$(find "$pictures/horizontal" "$pictures/tileable" -type f | shuf -n 1)

case $wallpaper in
    $pictures/horizontal/*)
        mode=fill;;
    $pictures/tileable/*)
        mode=tile;;
esac

feh --bg-"$mode" "$wallpaper"
