#!/bin/bash
#
# rofl - edit rofi's {,d}run history to put favourites on top

apps=(urxvt pcmanfm firefox deluge gimp audacity lxappearance pavucontrol)

for (( i = 0; i < ${#apps[@]}; i++ )) do
    (( priority = (${#apps[@]} - i) * 1000000 ))

    printf '%s %s\n' "$priority" "${apps[i],,}"       >&"$runfd"
    printf '%s %s\n' "$priority" "${apps[i]}.desktop" >&"$drunfd"
done {runfd}>  ~/.cache/rofi-3.runcache \
     {drunfd}> ~/.cache/rofi3.druncache
