#!/bin/bash
color0='#000507'
color8='#404040'
color1='#ff00dd'
color9=$color1
color2='#20f0df'
color10=$color2
color3=$color1
color11=$color1
color4=$color2
color12=$color4
color5=$color1
color13=$color5
color6=$color4
color14=$color4
color7='#ffffff'
color15='#ffffff'

dark=0

if (( dark )); then
    color7='#303030'
    color8='#555555'
    background=$color0
    foreground=$color15
    background_alt=$color7
    foreground_alt=$color8
else
    color7='#cccccc'
    color8='#e9e9e9'
    background=$color15
    foreground=$color0
    background_alt=$color8
    foreground_alt=$color7
fi

font='Dina'
font_size=10

X_font="xft:$font:pixelsize=$font_size, xft:lucy tewi:10, xft:Biwidth:pixelsize=12, xft:Symbola:pixelsize=12"
bar_font=("siji:pixelsize=10" "$font:pixelsize=$font_size" "$font:bold:pixelsize=$font_size" "lucy tewi:pixelsize=10" "Biwidth:pixelsize=12")
rofi_font='DinaOTB 8'
firefox_font="'$font', Biwidth"

border_width=0
window_gap=16
padding=16
