#!/bin/bash
#
# upload - upload files to the web

build_url() {
    local file=$1
    jq -nr --arg host "$host" --arg file "$file" '"https://\($host)/\($file | @uri )"'
}

host=up.v3lo.pw
remove=0

while getopts :lr o; do
    case $o in
        l)
            ls -tr sync/uploads | tail -n "${OPTARG:-1}" | while IFS= read -r file; do build_url "$file"; done
            exit
            ;;
        r)
            remove=1
            ;;
    esac
done
shift "$(( OPTIND - 1 ))"

source=$1

if [[ ! $source || $source == - ]]; then
    source=$(mktemp) || exit 1
    trap 'rm -f -- "$source"' exit
    cat > "$source"
    printf -v basename 'stdin-%(%F-%T)T.txt' -1
else
    source=$(realpath "$source")
    [[ -r $source ]] || exit 1
    basename=${source##*/}
fi

[[ -d $source ]] && source=${source%/}/

destination=${2:-$basename}

if [[ $source == ~/sync/*/* ]]; then
    base=${source#~/sync/}
    ssh "$host" bash -s "${base@Q}" "${destination@Q}" <<< 'rsync -rs --chmod=D755,F644 sync/"$1" sync/uploads/"$2"' || exit 1
else
    rsync -Pvrs --chmod=D755,F644 "$source" "$host:sync/uploads/$destination" || exit 1
fi

(( remove )) && rm -- "$source"

url=$(build_url "$destination")
printf '%s\n' "$url" | tee >(clip)

if [[ $(dunstify -t 10000 -A open,open -i network-server "uploaded $basename" "to $url") == open ]]; then
    exec xdg-open "$url"
fi &
