#!/bin/bash
#
# upload - upload files to the web

build_url() {
    local file=$1
    jq -nr --arg host "$host" --arg file "$file" '"https://\($host)/\($file | @uri )"'
}

host=up.monade.li
uploads_dir=sync/uploads
remove=0

while (( $# )); do
    case $1 in
        -l)
            shift
            n=${1:-1}
            find "$uploads_dir" -type f -printf '%T@/%P\0' | sort -znst / -k 1,1 | tail -zn "$n" |
            while IFS=/ read -rd '' time path; do
                build_url "$path"
            done
            exit
            ;;
        -r) remove=1;;
        *) break;;
    esac
    shift
done

source=$1
destination=$2
extension=

if [[ ! $source || $source == - ]]; then
    source=$(mktemp) || exit 1
    trap 'rm -f -- "$source"' exit
    cat > "$source"
else
    source=$(realpath "$source")
    [[ -r $source ]] || exit 1
    basename=${source##*/}
    [[ $basename == *.* ]] && extension=.${basename#*.}
fi

[[ -d $source ]] && source=${source%/}/

if [[ ! $destination ]]; then
    destination=$(base64 /dev/urandom | tr -cd '[:alnum:]' | head -c 6)$extension
elif [[ $destination != *.* ]]; then
    destination+=$extension
fi

if [[ $source == ~/sync/*/* ]]; then
    printf 'rsync -vrs --chmod=D755,F644 %q %q\n' "sync/${source#~/sync/}" "$uploads_dir/$destination" | ssh "$host" bash || exit 1
else
    rsync -Pvrs --chmod=D755,F644 "$source" "$host:$uploads_dir/$destination" || exit 1
fi

(( remove )) && rm -- "$source"

url=$(build_url "$destination")
printf '%s\n' "$url" | tee >(clip)

if [[ $(dunstify -t 10000 -A open,open -i network-server "uploaded $basename" "to $url") == open ]]; then
    exec xdg-open "$url"
fi &
