#!/bin/bash
#
# upload - upload files to the web

build_url() {
    local file=$1
    jq -nr --arg host "$host" --arg file "$file" '"https://\($host)/\($file | @uri )"'
}

host=up.v3lo.pw
remove=0

while (( $# )); do
    case $1 in
        -l)
            shift
            n=${1:-1}
            eval "sorted=( $(ls -tr --quoting-style=shell-escape sync/uploads) )"
            for f in "${sorted[@]:(-n)}"; do
                build_url "$f"
            done
            exit
            ;;
        -r) remove=1;;
        *) break;;
    esac
    shift
done

source=$1
destination=$2
extension=

if [[ ! $source || $source == - ]]; then
    source=$(mktemp) || exit 1
    trap 'rm -f -- "$source"' exit
    cat > "$source"
else
    source=$(realpath "$source")
    [[ -r $source ]] || exit 1
    basename=${source##*/}
    [[ $basename == *.* ]] && extension=.${basename#*.}
fi

[[ -d $source ]] && source=${source%/}/

if [[ ! $destination ]]; then
    destination=$(printf '%(%s)T %s' -1 "$RANDOM" | sha256sum | cut -d ' ' -f 1 | base64 | head -c 6)$extension
elif [[ $destination != *.* ]]; then
    destination+=$extension
fi

if [[ $source == ~/sync/*/* ]]; then
    base=${source#~/sync/}
    ssh "$host" bash -s "${base@Q}" "${destination@Q}" <<< 'rsync -rs --chmod=D755,F644 sync/"$1" sync/uploads/"$2"' || exit 1
else
    rsync -Pvrs --chmod=D755,F644 "$source" "$host:sync/uploads/$destination" || exit 1
fi

(( remove )) && rm -- "$source"

url=$(build_url "$destination")
printf '%s\n' "$url" | tee >(clip)

if [[ $(dunstify -t 10000 -A open,open -i network-server "uploaded $basename" "to $url") == open ]]; then
    exec xdg-open "$url"
fi &
