#!/bin/bash
#
# wallpaper - control the wallpaper

case $1 in
random)
    IFS= read -rd '' wallpaper < <(find "$(xdg-user-dir PICTURES)"/wallpapers -maxdepth 1 -type f -print0 | shuf -zn 1)
    printf '%s\n' "$wallpaper"
    feh --bg-fill "$wallpaper"
    ;;
esac
